pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-login')
        IMAGE_NAME = 'ashabtariq12/k8s-pod-metric-viewer'
        IMAGE_TAG = 'V1.0'
        SONAR_TOKEN = credentials('SONAR_TOKEN')
        SONAR_HOST_URL = 'http://192.168.1.40:9000'
        SONAR_PROJECT_KEY = 'k8s-pods-metrics-viewer'
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/ashabtariq/k8s-pod-metrics-viewer.git'
            }
        }

        // stage('SonarQube Analysis') {
        //     steps {
        //         dir('ci') { // Adjust this to where your sonar-project.properties file is
        //             withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
        //                 sh '''
        //                     echo "Running SonarQube scan..."
        //                     sonar-scanner -Dsonar.login=$SONAR_TOKEN
        //                 '''
        //             }
        //         }
        //     }
        // }

        stage('Build Docker Image') {
            steps {
                dir('app') { // Navigate to the app directory
                    sh '''
                        echo "Current directory: $(pwd)"
                        ls -l
                        docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
                    '''
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                sh '''
                    echo "$DOCKERHUB_CREDENTIALS_PSW" | docker login -u "$DOCKERHUB_CREDENTIALS_USR" --password-stdin
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                '''
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully'
        }
        failure {
            echo 'Pipeline failed'
        }
    }
}
