pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-login')
        IMAGE_NAME = 'ashabtariq12/k8s-pod-metric-viewer'
        IMAGE_TAG = 'V1.0'
        SONAR_TOKEN = credentials('SONAR_TOKEN')
        SONAR_HOST_URL = 'http://192.168.1.40:9000'
        SONAR_PROJECT_KEY = 'k8s-pods-metrics-viewer'
    }
    stages {
        stage('Checkout Code') {
            steps {
                git branch: 'master', url: 'https://github.com/ashabtariq/k8s-pod-metrics-viewer.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('/ci') { // Make sure sonar-project.properties is here
                    withCredentials([string(credentialsId: 'SONAR_TOKEN', variable: 'SONAR_TOKEN')]) {
                        sh '''
                            echo "Running SonarQube scan..."
                            sonar-scanner -Dsonar.login=$SONAR_TOKEN
                        '''
                    }
                }
            }

            stage('Go to Directory and Build') {
                steps {
                    sh '''
                    cd app || exit 1
                    echo "Current directory: $(pwd)"
                    # Now run commands in this directory
                    ls -l
                    docker build -t ashabtariq12/k8s-pod-metric-viewer:V1.0 .
                '''
                }
            }

            stage('Push to Docker Hub') {
                steps {
                    sh '''
                    echo "$DOCKERHUB_CREDENTIALS_PSW" | docker login -u "$DOCKERHUB_CREDENTIALS_USR" --password-stdin
                    docker push ${IMAGE_NAME}:${IMAGE_TAG}
                '''
                }
            }
        }
    }
}
